In [6]:
a=[1,2,3,4]
for i,el in enumerate(a):
    print('index:',i, 'element:',el)
    

index: 0 element: 1
index: 1 element: 2
index: 2 element: 3
index: 3 element: 4


In [7]:
while True:
    pass

KeyboardInterrupt: 

In [24]:
import numpy as np
a=np.random.rand(3,5)
print(a)
a.dtype
b=np.zeros((3,5))
print(b)
c=np.ones((2,3))*3
print(c)
#identity matrix
d=np.eye(3)
print(d)
e=np.asarray([1,2,3])
print(e)
print(type(d[0].shape))

[[0.18017863 0.19500287 0.04986107 0.00944437 0.82642631]
 [0.81609713 0.57892416 0.60985485 0.19084745 0.37612549]
 [0.88382081 0.27123052 0.49792683 0.12191459 0.30753981]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[3. 3. 3.]
 [3. 3. 3.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 2 3]
<class 'tuple'>


In [35]:
x_1d=np.arange(50)
print(x_1d[-10:])
x_2d = np.arange(50).reshape(5, 10)
print(x_2d)
print(x_2d[:,1])
for i in x_2d.flat[:5]:
    print (i)

[40 41 42 43 44 45 46 47 48 49]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]]
[ 1 11 21 31 41]
0
1
2
3
4
