In [30]:
import netCDF4 as ncf
import numpy as np
fN = '../data/HadEX2_GSL.nc'

!ncdump -h {fN} #show header of file 

ncdump [-c|-h] [-v ...] [[-b|-f] [c|f]] [-l len] [-n name] [-p n[,n]] [-k] [-x] [-s] [-t|-i] [-g ...] [-w] [-Ln] file
  [-c]             Coordinate variable data and header information
  [-h]             Header information only, no data
  [-v var1[,...]]  Data for variable(s) <var1>,... only
  [-b [c|f]]       Brief annotations for C or Fortran indices in data
  [-f [c|f]]       Full annotations for C or Fortran indices in data
  [-l len]         Line length maximum in data section (default 80)
  [-n name]        Name for netCDF (default derived from file name)
  [-p n[,n]]       Display floating-point values with less precision
  [-k]             Output kind of netCDF file
  [-s]             Output special (virtual) attributes
  [-t]             Output time data as date-time strings
  [-i]             Output time data as date-time strings with ISO-8601 'T' separator
  [-g grp1[,...]]  Data and metadata for group(s) <grp1>,... only
  [-w]             With client-side caching of variabl

In [19]:
ncf=nc.Dataset(fN) #open the dataset
print(ncf)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4_CLASSIC data model, file format HDF5):
    data: Growing season length
    source: HadEX2 (http://www.climdex.org/)
    reference: Donat et al., 2013
    dimensions(sizes): lon(96), lat(73), time(50)
    variables(dimensions): float64 lon(lon), float64 lat(lat), int32 time(time), float32 GSL(time,lat,lon), float64 trend(lat,lon), float64 p_val(lat,lon)
    groups: 



In [20]:
print(ncf.variables.keys()) #get all variables

odict_keys(['lon', 'lat', 'time', 'GSL', 'trend', 'p_val'])


In [21]:
print(ncf.variables['lon']) #still contains meta data like units - requires further index

<class 'netCDF4._netCDF4.Variable'>
float64 lon(lon)
    _FillValue: nan
unlimited dimensions: 
current shape = (96,)
filling on


In [22]:
print(ncf.variables['lon'][:]) #now you get the data

[  0.     3.75   7.5   11.25  15.    18.75  22.5   26.25  30.    33.75
  37.5   41.25  45.    48.75  52.5   56.25  60.    63.75  67.5   71.25
  75.    78.75  82.5   86.25  90.    93.75  97.5  101.25 105.   108.75
 112.5  116.25 120.   123.75 127.5  131.25 135.   138.75 142.5  146.25
 150.   153.75 157.5  161.25 165.   168.75 172.5  176.25 180.   183.75
 187.5  191.25 195.   198.75 202.5  206.25 210.   213.75 217.5  221.25
 225.   228.75 232.5  236.25 240.   243.75 247.5  251.25 255.   258.75
 262.5  266.25 270.   273.75 277.5  281.25 285.   288.75 292.5  296.25
 300.   303.75 307.5  311.25 315.   318.75 322.5  326.25 330.   333.75
 337.5  341.25 345.   348.75 352.5  356.25]


In [23]:
print(ncf.variables['time'].units) # what we mean by units

days since 1956-01-01 00:00:00


In [24]:
lat=ncf.variables['lat'][:]
print(lat)

[-90.  -87.5 -85.  -82.5 -80.  -77.5 -75.  -72.5 -70.  -67.5 -65.  -62.5
 -60.  -57.5 -55.  -52.5 -50.  -47.5 -45.  -42.5 -40.  -37.5 -35.  -32.5
 -30.  -27.5 -25.  -22.5 -20.  -17.5 -15.  -12.5 -10.   -7.5  -5.   -2.5
   0.    2.5   5.    7.5  10.   12.5  15.   17.5  20.   22.5  25.   27.5
  30.   32.5  35.   37.5  40.   42.5  45.   47.5  50.   52.5  55.   57.5
  60.   62.5  65.   67.5  70.   72.5  75.   77.5  80.   82.5  85.   87.5
  90. ]


In [27]:
trend_masked = ncf.variables['trend'][:]
trend_masked
#trend is a masked array containing the data and the mask

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [34]:
#a little on masks
ma=np.ma.array([0.,1.,2.],mask=[True,False,False],fill_value=np.NaN) 
ma 
#for the array [0,1,2], if true fill with fill value according to mask = [nan,1,2]
#data has to be float

masked_array(data=[--, 1.0, 2.0],
             mask=[ True, False, False],
       fill_value=nan)

In [35]:
#mask arrays can be converteed to nan arrays
trend=np.asarray(trend_masked)
trend

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])

In [37]:
import xarray as xr

In [38]:
ds=xr.open_dataset(fN) #open dataset using xarray this time
#datasets contain a bunch of data arrays
#when reading a variable, we are reading the data array

In [39]:
lat=ds['lat'] #or ds.lat
lat

<xarray.DataArray 'lat' (lat: 73)>
array([-90. , -87.5, -85. , -82.5, -80. , -77.5, -75. , -72.5, -70. , -67.5,
       -65. , -62.5, -60. , -57.5, -55. , -52.5, -50. , -47.5, -45. , -42.5,
       -40. , -37.5, -35. , -32.5, -30. , -27.5, -25. , -22.5, -20. , -17.5,
       -15. , -12.5, -10. ,  -7.5,  -5. ,  -2.5,   0. ,   2.5,   5. ,   7.5,
        10. ,  12.5,  15. ,  17.5,  20. ,  22.5,  25. ,  27.5,  30. ,  32.5,
        35. ,  37.5,  40. ,  42.5,  45. ,  47.5,  50. ,  52.5,  55. ,  57.5,
        60. ,  62.5,  65. ,  67.5,  70. ,  72.5,  75. ,  77.5,  80. ,  82.5,
        85. ,  87.5,  90. ])
Coordinates:
  * lat      (lat) float64 -90.0 -87.5 -85.0 -82.5 -80.0 ... 82.5 85.0 87.5 90.0

In [41]:
lon=ds.lon
lon
#but not entirely a numpy array now - still some meta i guess

<xarray.DataArray 'lon' (lon: 96)>
array([  0.  ,   3.75,   7.5 ,  11.25,  15.  ,  18.75,  22.5 ,  26.25,  30.  ,
        33.75,  37.5 ,  41.25,  45.  ,  48.75,  52.5 ,  56.25,  60.  ,  63.75,
        67.5 ,  71.25,  75.  ,  78.75,  82.5 ,  86.25,  90.  ,  93.75,  97.5 ,
       101.25, 105.  , 108.75, 112.5 , 116.25, 120.  , 123.75, 127.5 , 131.25,
       135.  , 138.75, 142.5 , 146.25, 150.  , 153.75, 157.5 , 161.25, 165.  ,
       168.75, 172.5 , 176.25, 180.  , 183.75, 187.5 , 191.25, 195.  , 198.75,
       202.5 , 206.25, 210.  , 213.75, 217.5 , 221.25, 225.  , 228.75, 232.5 ,
       236.25, 240.  , 243.75, 247.5 , 251.25, 255.  , 258.75, 262.5 , 266.25,
       270.  , 273.75, 277.5 , 281.25, 285.  , 288.75, 292.5 , 296.25, 300.  ,
       303.75, 307.5 , 311.25, 315.  , 318.75, 322.5 , 326.25, 330.  , 333.75,
       337.5 , 341.25, 345.  , 348.75, 352.5 , 356.25])
Coordinates:
  * lon      (lon) float64 0.0 3.75 7.5 11.25 15.0 ... 345.0 348.8 352.5 356.2

In [48]:
#convert to numpy
lat_dat=lat.values[:]
lon_dat=np.asarray(lon)[:]
#two ways

array([  0.  ,   3.75,   7.5 ,  11.25,  15.  ,  18.75,  22.5 ,  26.25,
        30.  ,  33.75,  37.5 ,  41.25,  45.  ,  48.75,  52.5 ,  56.25,
        60.  ,  63.75,  67.5 ,  71.25,  75.  ,  78.75,  82.5 ,  86.25,
        90.  ,  93.75,  97.5 , 101.25, 105.  , 108.75, 112.5 , 116.25,
       120.  , 123.75, 127.5 , 131.25, 135.  , 138.75, 142.5 , 146.25,
       150.  , 153.75, 157.5 , 161.25, 165.  , 168.75, 172.5 , 176.25,
       180.  , 183.75, 187.5 , 191.25, 195.  , 198.75, 202.5 , 206.25,
       210.  , 213.75, 217.5 , 221.25, 225.  , 228.75, 232.5 , 236.25,
       240.  , 243.75, 247.5 , 251.25, 255.  , 258.75, 262.5 , 266.25,
       270.  , 273.75, 277.5 , 281.25, 285.  , 288.75, 292.5 , 296.25,
       300.  , 303.75, 307.5 , 311.25, 315.  , 318.75, 322.5 , 326.25,
       330.  , 333.75, 337.5 , 341.25, 345.  , 348.75, 352.5 , 356.25])

In [50]:
trend=ds.trend
trend 
#not presented as masked array like netcdf

<xarray.DataArray 'trend' (lat: 73, lon: 96)>
array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]])
Coordinates:
  * lon      (lon) float64 0.0 3.75 7.5 11.25 15.0 ... 345.0 348.8 352.5 356.2
  * lat      (lat) float64 -90.0 -87.5 -85.0 -82.5 -80.0 ... 82.5 85.0 87.5 90.0

In [69]:
#select a subset of data according to coordinates by xarray
GSL=ds.GSL
#say yu want data from lat:30,50 lon: -150-85
lat = slice(30, 50)
lon = slice(360 - 105, 360 - 85)

GSL_CNA = GSL.sel(lat=lat, lon=lon)

print('Shape of the data:')
print(' * all:', GSL.shape)
print(' * CNA:', GSL_CNA.shape)


Shape of the data:
 * all: (50, 73, 96)
 * CNA: (50, 9, 6)


In [54]:
# Note on slice: the following two commands are equivalent:

# GSL.values[:10]
# GSL.values[slice(0, 10)]
# However the : operator only works in square brackets ([]). So for functions like GSL.sel(...) we need to use slice

In [55]:
GSL_CNA.lon

<xarray.DataArray 'lon' (lon: 6)>
array([255.  , 258.75, 262.5 , 266.25, 270.  , 273.75])
Coordinates:
  * lon      (lon) float64 255.0 258.8 262.5 266.2 270.0 273.8

In [57]:
#if you want to do it for a location and not a range say  47 E 8N
lat=47
lon=8

GSL_SW=GSL.sel(lat=lat,lon=lon, method='nearest')

GSL_SW.shape
#data is one dimensional now (in time)

(50,)

In [67]:
GSL_SW_60=GSL_SW.sel(time=slice('1960','1961'))

#or for 1 value
GSL_CNA_60=GSL_CNA.sel(time='1960')

GSL_SW_60.shape

GSL_SW60_array=GSL_SW_60.values[:]

GSL_SW60_array


array([266.95663, 260.41937], dtype=float32)

In [70]:
GSL.mean('time')


<xarray.DataArray 'GSL' (lat: 73, lon: 96)>
array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float32)
Coordinates:
  * lon      (lon) float64 0.0 3.75 7.5 11.25 15.0 ... 345.0 348.8 352.5 356.2
  * lat      (lat) float64 -90.0 -87.5 -85.0 -82.5 -80.0 ... 82.5 85.0 87.5 90.0

In [74]:
GSL_CNA.mean(('lat', 'lon')) #mean over more than one dimension possible

<xarray.DataArray 'GSL' (time: 50)>
array([263.1372 , 260.5882 , 266.3644 , 247.30276, 263.59653, 254.37766,
       265.84784, 266.60938, 261.76404, 263.3224 , 260.81277, 259.2541 ,
       266.03784, 252.17351, 255.83366, 259.07184, 254.93245, 262.94714,
       267.47083, 256.11783, 253.93668, 266.5638 , 249.51796, 239.0446 ,
       251.0114 , 271.1867 , 260.69168, 261.5591 , 260.14377, 254.08524,
       269.4333 , 265.77594, 261.84576, 259.86154, 264.63736, 254.87657,
       263.09467, 253.68837, 267.56207, 265.9866 , 254.00482, 253.2385 ,
       271.10004, 273.8884 , 261.81857, 265.27493, 248.62473, 259.81198,
       267.09018, 266.4215 ], dtype=float32)
Coordinates:
  * time     (time) datetime64[ns] 1956-01-01 1957-01-01 ... 2005-01-01